from google import genai
import os

def get_gemini_advice(api_key, ticker, current_price, predictions, history_summary=None):
    """
    Generates trading advice using Google Gemini based on predictions.

    Args:
        api_key (str): Google Gemini API Key.
        ticker (str): Stock ticker symbol.
        current_price (float): The most recent known price.
        predictions (dict): Dictionary of horizon (days) -> predicted price.
        history_summary (str, optional): Summary of recent historical trends.

    Returns:
        str: Advice text generated by Gemini.
    """
    if not api_key:
        return " Please provide a valid Google Gemini API Key in the sidebar to get AI advice."

    try:
        client = genai.Client(api_key=api_key)

        prompt = f"""
        You are an expert financial advisor and stock market analyst.
        
        I need your analysis and advice for the stock **{ticker}**.
        
        **Current Status:**
        - Current Price: ${current_price:.2f}
        
        **AI Model Predictions (LSTM):**
        """
        
        for horizon, price in predictions.items():
            change = ((price - current_price) / current_price) * 100
            direction = "UP" if change > 0 else "DOWN"
            prompt += f"- {horizon} Days: ${price:.2f} ({direction} {change:.2f}%)\n"
            
        if history_summary:
            prompt += f"\n**Recent History Context:**\n{history_summary}\n"
            
        prompt += """
        
        Based on these predictions and general market knowledge about this stock, please provide:
        1. **Short-term Outlook**: What should a trader do in the next few weeks?
        2. **Long-term Strategy**: Is this a good hold for the next 6 months?
        3. **Risk Factors**: What specific risks should be considered for this stock right now?
        4. **Recommendation**: Buy, Sell, or Hold?
        
        Please be concise, professional, and include a disclaimer that this is for informational purposes only.
        """

        response = client.models.generate_content(
            model="gemini-2.5-flash", contents=prompt
        )
        return response.text

    except Exception as e:
        return f" Error generating advice: {str(e)}"
